const path = {
    home: '/',
    dashboard: '/dashboard',
    login: '/login',
    vehicleBrand: '/vehicle-brands',
    vehicleModel: '/vehicle-models',
    contract: '/contracts',
    vehicle: "/vehicles",
    vehicleDetail: "/vehicles/:id",
    station: "/stations",
    operator: "/operators",
    coOwnerGroup: "/co-owner-groups",
    coOwnerGroupDetail: "/co-owner-groups/:id",
    booking: "/bookings",
    bookingDetail: "/bookings/:id",
    expenseFee: "/expense-fees",
    expenseFeeDetail: "/expense-fees/:id",
    member: "/members",
    invoice: "/invoices",
    staff: "/staff",
    withdraw: "/withdraws",
    profile: "/profile",
} as const

export default path